# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # - name: Build Arch Linux Package
      #   # You may pin to the exact commit or the version.
      #   # uses: Menci/build-archlinux-package@2bf49233cc85786df75aa750e1d6c994e534395d
      #   uses: Menci/build-archlinux-package@beta-v1
      #   with:
      #     pkgbuild-directory: $HOME
      #     target-directory: $HOME/packages

      # - name: Build ArchLinux Packages
      #   # You may pin to the exact commit or the version.
      #   # uses: zjuyk/pkgbuild-aur@a660603570d1d8e2f4a40f36065f59b5bd474b03
      #   uses: zjuyk/pkgbuild-aur@v1.0
      #   with:
      #     # ArchLinux package name to build
      #     pkg-name: fjordlauncherunlocked

      - name: Archlinux MAKEPKG builder
        uses: ktcar214/arch-makepkg-action@v1.0.11
              
